apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: demo
resources:
  - ../../base
  - service-account.yaml
patches:
  - path: patch-azure-env.yaml
    target:
      kind: Deployment
  - path: patch-workload-identity.yaml
    target:
      kind: Deployment
      name: concierge|ops-agent
configMapGenerator:
  - name: azure-config
    envs:
      - azure.config.env
secretGenerator:
  - name: azure-secrets
    envs:
      - azure.secret.env
generatorOptions:
  disableNameSuffixHash: true
replacements:
  - source:
      kind: ConfigMap
      name: azure-config
      fieldPath: data.FOUNDRY_WORKLOAD_IDENTITY_CLIENT_ID
    targets:
      - select:
          kind: ServiceAccount
          name: demo
        fieldPaths:
          - metadata.annotations.[azure.workload.identity/client-id]
  - source:
      kind: ConfigMap
      name: azure-config
      fieldPath: data.APP_VERSION
    targets:
      - select:
          kind: Deployment
          name: sundae-mcp
        fieldPaths:
          - spec.template.spec.containers.[name=sundae-mcp].image
        options:
          delimiter: ":"
          index: 1
      - select:
          kind: Deployment
          name: ops-agent
        fieldPaths:
          - spec.template.spec.containers.[name=ops-agent].image
          - spec.template.spec.initContainers.[name=wait-for-sundae-mcp].image
        options:
          delimiter: ":"
          index: 1
      - select:
          kind: Deployment
          name: concierge
        fieldPaths:
          - spec.template.spec.containers.[name=concierge].image
        options:
          delimiter: ":"
          index: 1
images:
  - name: sundae-funday/sundae-mcp
    newName: ghcr.io/pauldotyu/sundae-funday-sundae-mcp
  - name: sundae-funday/ops-agent
    newName: ghcr.io/pauldotyu/sundae-funday-ops-agent
  - name: sundae-funday/concierge
    newName: ghcr.io/pauldotyu/sundae-funday-concierge
