apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
patches:
  - path: patch-configmap.yaml
images:
  - name: sundae-funday/sundae-mcp
    newName: REPLACE_ME_ACR/sundae-mcp
    newTag: 0.1.0
  - name: sundae-funday/ops-agent
    newName: REPLACE_ME_ACR/ops-agent
    newTag: 0.1.0
  - name: sundae-funday/concierge
    newName: REPLACE_ME_ACR/concierge
    newTag: 0.1.0
