apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: sundae-funday
data:
  OTEL_EXPORTER_OTLP_ENDPOINT: https://not-used.invalid
  APPLICATIONINSIGHTS_CONNECTION_STRING: REPLACE_ME_APPINSIGHTS_CONNECTION_STRING
  OPENAI_BASE_URL: REPLACE_ME_OPENAI_BASE_URL
  OPENAI_CHAT_MODEL: REPLACE_ME_OPENAI_CHAT_MODEL
  OPENAI_AUTH_MODE: api_key
  OPENAI_API_KEY: REPLACE_ME_OPENAI_API_KEY
