- op: add
  path: /spec/template/spec/containers/0/envFrom/-
  value:
    configMapRef:
      name: azure-config
- op: add
  path: /spec/template/spec/containers/0/envFrom/-
  value:
    secretRef:
      name: azure-secrets
