apiVersion: v1
kind: Service
metadata:
  name: concierge
  namespace: demo
  labels:
    app.kubernetes.io/name: concierge
    app.kubernetes.io/component: web
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: concierge
  ports:
    - name: http
      port: 80
      targetPort: http
