apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: sundae-funday
resources:
  - namespace.yaml
  - configmap.yaml
  - sundae-mcp-deployment.yaml
  - sundae-mcp-service.yaml
  - ops-agent-deployment.yaml
  - ops-agent-service.yaml
  - concierge-deployment.yaml
  - concierge-service.yaml
labels:
  - pairs:
      app.kubernetes.io/part-of: sundae-funday
      app.kubernetes.io/managed-by: kustomize
