apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configMap.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "sundae-funday.labels" . | nindent 4 }}
    app.kubernetes.io/name: sundae-funday
    app.kubernetes.io/component: config
data:
  APP_VERSION: {{ include "sundae-funday.version" . | quote }}
  {{- range $name, $value := .Values.config }}
  {{ $name }}: {{ $value | quote }}
  {{- end }}
