{{- if and .Values.secret.create (not .Values.secret.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "sundae-funday.labels" . | nindent 4 }}
    app.kubernetes.io/name: sundae-funday
    app.kubernetes.io/component: secrets
type: Opaque
stringData:
  {{- range $name, $value := .Values.secret.data }}
  {{ $name }}: {{ $value | quote }}
  {{- end }}
{{- end }}
