apiVersion: v1
kind: Service
metadata:
  name: loki
  namespace: demo
spec:
  selector:
    app: loki
  ports:
    - name: http
      port: 3100
      targetPort: http-metrics
      protocol: TCP
    - name: grpc
      port: 9095
      targetPort: grpc
      protocol: TCP
  type: ClusterIP
