apiVersion: v1
kind: Service
metadata:
  name: tempo
  namespace: demo
spec:
  selector:
    app: tempo
  ports:
    - name: http
      port: 3200
      targetPort: http
      protocol: TCP
    - name: otlp-grpc
      port: 4317
      targetPort: grpc-otlp
      protocol: TCP
    - name: otlp-http
      port: 4318
      targetPort: http-otlp
      protocol: TCP
    - name: jaeger-thrift
      port: 6831
      targetPort: jaeger-thrift
      protocol: UDP
    - name: jaeger-http
      port: 14268
      targetPort: jaeger-http
      protocol: TCP
  type: ClusterIP
